# Repository settings for linode-kubernetes-cluster
# https://github.com/repository-settings/app

repository:
  name: linode-kubernetes-cluster
  description: Simple, clean OpenTofu template for deploying cost-effective Kubernetes clusters on Linode (LKE) with optional monitoring stack
  homepage: https://github.com/idvoretskyi/linode-kubernetes-cluster
  topics:
    - kubernetes
    - linode
    - lke
    - opentofu
    - terraform
    - infrastructure-as-code
    - prometheus
    - grafana
    - monitoring
    - devops
    - cloud-native

  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: false
  delete_branch_on_merge: true

  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  # Type labels
  - name: bug
    color: d73a4a
    description: Something isn't working

  - name: enhancement
    color: a2eeef
    description: New feature or request

  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation

  # Priority labels
  - name: priority:high
    color: e99695
    description: High priority issue

  - name: priority:medium
    color: fbca04
    description: Medium priority issue

  - name: priority:low
    color: d4c5f9
    description: Low priority issue

  # Component labels
  - name: component:infrastructure
    color: 1d76db
    description: Core infrastructure code (cluster, firewall)

  - name: component:monitoring
    color: 1d76db
    description: Monitoring module (Prometheus, Grafana, metrics-server)

  - name: component:docs
    color: 0075ca
    description: Documentation updates

  # Status labels
  - name: status:ready
    color: 0e8a16
    description: Ready to be worked on

  - name: status:in-progress
    color: fbca04
    description: Currently being worked on

  - name: status:blocked
    color: d73a4a
    description: Blocked by another issue or dependency

  - name: good first issue
    color: 7057ff
    description: Good for newcomers

  - name: help wanted
    color: 008672
    description: Extra attention is needed

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
      required_status_checks:
        strict: false
        contexts: []
      enforce_admins: false
      required_linear_history: false
      restrictions: null
